version: "3.8"
services:
  database:
    image: mysql
    command: --init-file /structure.sql
    environment:
      MYSQL_DATABASE: oldgrounds
      MYSQL_PASSWORD: sample
      MYSQL_ROOT_PASSWORD: sample
    ports:
      - "3306:3306"
    volumes:
      - ./website/structure.sql:/structure.sql
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
  oldgrounds:
    build: ./
    ports:
      - "80:80"
    volumes:
      - ./container/website/logs/nginx:/var/log/nginx
      - ./container/website/data:/var/www/data